import { Achievement } from '../types/mission';

export const ALL_ACHIEVEMENTS: Achievement[] = [
  { achievementId: 'ach_tap_100', title: 'タッパー', description: 'スライムを100回タップ', type: 'tap_slimes', targetValue: 100, currentValue: 0, rewardCoins: 200, rewardGems: 1, unlocked: false, unlockedAt: null, icon: 'finger-print' },
  { achievementId: 'ach_tap_1000', title: 'マスタータッパー', description: 'スライムを1000回タップ', type: 'tap_slimes', targetValue: 1000, currentValue: 0, rewardCoins: 1000, rewardGems: 5, unlocked: false, unlockedAt: null, icon: 'hand-left' },
  { achievementId: 'ach_tap_10000', title: '伝説のタッパー', description: 'スライムを10000回タップ', type: 'tap_slimes', targetValue: 10000, currentValue: 0, rewardCoins: 5000, rewardGems: 15, unlocked: false, unlockedAt: null, icon: 'star' },
  { achievementId: 'ach_merge_10', title: 'はじめての合体', description: '10回合体', type: 'merge_slimes', targetValue: 10, currentValue: 0, rewardCoins: 200, rewardGems: 1, unlocked: false, unlockedAt: null, icon: 'git-merge' },
  { achievementId: 'ach_merge_100', title: '合体マスター', description: '100回合体', type: 'merge_slimes', targetValue: 100, currentValue: 0, rewardCoins: 1000, rewardGems: 5, unlocked: false, unlockedAt: null, icon: 'flash' },
  { achievementId: 'ach_merge_500', title: '合体の達人', description: '500回合体', type: 'merge_slimes', targetValue: 500, currentValue: 0, rewardCoins: 3000, rewardGems: 10, unlocked: false, unlockedAt: null, icon: 'trophy' },
  { achievementId: 'ach_coins_1k', title: '貯金箱', description: '累計1,000コイン', type: 'earn_coins', targetValue: 1000, currentValue: 0, rewardCoins: 300, rewardGems: 1, unlocked: false, unlockedAt: null, icon: 'cash' },
  { achievementId: 'ach_coins_10k', title: '金庫番', description: '累計10,000コイン', type: 'earn_coins', targetValue: 10000, currentValue: 0, rewardCoins: 1000, rewardGems: 3, unlocked: false, unlockedAt: null, icon: 'wallet' },
  { achievementId: 'ach_coins_100k', title: '大富豪', description: '累計100,000コイン', type: 'earn_coins', targetValue: 100000, currentValue: 0, rewardCoins: 5000, rewardGems: 10, unlocked: false, unlockedAt: null, icon: 'diamond' },
  { achievementId: 'ach_coins_1m', title: 'スライム長者', description: '累計1,000,000コイン', type: 'earn_coins', targetValue: 1000000, currentValue: 0, rewardCoins: 10000, rewardGems: 25, unlocked: false, unlockedAt: null, icon: 'planet' },
  { achievementId: 'ach_discover_5', title: '探検家', description: '5種発見', type: 'discover_new', targetValue: 5, currentValue: 0, rewardCoins: 300, rewardGems: 2, unlocked: false, unlockedAt: null, icon: 'search' },
  { achievementId: 'ach_discover_15', title: 'コレクター', description: '15種発見', type: 'discover_new', targetValue: 15, currentValue: 0, rewardCoins: 1000, rewardGems: 5, unlocked: false, unlockedAt: null, icon: 'albums' },
  { achievementId: 'ach_discover_30', title: 'マスターコレクター', description: '30種発見', type: 'discover_new', targetValue: 30, currentValue: 0, rewardCoins: 3000, rewardGems: 10, unlocked: false, unlockedAt: null, icon: 'ribbon' },
  { achievementId: 'ach_discover_all', title: '図鑑コンプリート', description: '全種発見', type: 'fill_encyclopedia', targetValue: 38, currentValue: 0, rewardCoins: 10000, rewardGems: 50, unlocked: false, unlockedAt: null, icon: 'book' },
  { achievementId: 'ach_rare_1', title: 'レアハンター', description: 'レア以上を初合成', type: 'collect_rare', targetValue: 1, currentValue: 0, rewardCoins: 500, rewardGems: 2, unlocked: false, unlockedAt: null, icon: 'sparkles' },
  { achievementId: 'ach_epic_1', title: 'エピックハンター', description: 'エピック以上を初合成', type: 'collect_rare', targetValue: 1, currentValue: 0, rewardCoins: 1000, rewardGems: 5, unlocked: false, unlockedAt: null, icon: 'flame' },
  { achievementId: 'ach_legendary_1', title: 'レジェンドハンター', description: 'レジェンダリーを初合成', type: 'collect_rare', targetValue: 1, currentValue: 0, rewardCoins: 3000, rewardGems: 10, unlocked: false, unlockedAt: null, icon: 'shield' },
  { achievementId: 'ach_mythic_1', title: '神話への到達', description: 'ミシック初合成', type: 'reach_mythic', targetValue: 1, currentValue: 0, rewardCoins: 5000, rewardGems: 15, unlocked: false, unlockedAt: null, icon: 'sunny' },
  { achievementId: 'ach_mythic_all', title: '全色制覇', description: '全6色のミシック合成', type: 'reach_mythic', targetValue: 6, currentValue: 0, rewardCoins: 15000, rewardGems: 30, unlocked: false, unlockedAt: null, icon: 'rainbow' },
  { achievementId: 'ach_login_7', title: '1週間の常連', description: '7日連続ログイン', type: 'login_streak', targetValue: 7, currentValue: 0, rewardCoins: 500, rewardGems: 3, unlocked: false, unlockedAt: null, icon: 'calendar' },
  { achievementId: 'ach_login_30', title: '1ヶ月の牧場主', description: '30日連続ログイン', type: 'login_streak', targetValue: 30, currentValue: 0, rewardCoins: 3000, rewardGems: 15, unlocked: false, unlockedAt: null, icon: 'calendar' },
  { achievementId: 'ach_login_100', title: '100日の猛者', description: '100日連続ログイン', type: 'login_streak', targetValue: 100, currentValue: 0, rewardCoins: 10000, rewardGems: 30, unlocked: false, unlockedAt: null, icon: 'medal' },
  { achievementId: 'ach_deco_5', title: 'デコレーター', description: '装飾を5個設置', type: 'buy_decoration', targetValue: 5, currentValue: 0, rewardCoins: 1000, rewardGems: 3, unlocked: false, unlockedAt: null, icon: 'color-palette' },
  { achievementId: 'ach_deco_all', title: '夢の牧場', description: '全装飾を設置', type: 'buy_decoration', targetValue: 10, currentValue: 0, rewardCoins: 5000, rewardGems: 15, unlocked: false, unlockedAt: null, icon: 'home' },
  { achievementId: 'ach_ad_50', title: 'スポンサーの友', description: 'リワード広告50回視聴', type: 'watch_ad', targetValue: 50, currentValue: 0, rewardCoins: 2000, rewardGems: 10, unlocked: false, unlockedAt: null, icon: 'videocam' },
];
